### Training GNNs ##############################################################

##' @title Training GNNs
##' @param dim see ?GMMN_model or ?VAE_model
##' @param data (n,d)-matrix containing n d-dimensional observations forming the
##'        training data
##' @param batch.size number of samples per stochastic gradient step
##' @param nepoch number of epochs (one epoch equals one pass through the complete
##'        training dataset while updating the GNN's parameters)
##' @param type the type of GNN to train
##' @param ... additional arguments passed to the underlying GMMN_model()
##' @return trained GNN
##' @author Marius Hofert
train <- function(dim, data, batch.size, nepoch, type = c("GMMN", "VAE"), ...)
{
    type <- match.arg(type)
    if(!is.matrix(data))
        stop("'data' needs to be an (n, d)-matrix containing n d-dimensional training observations.")
    dim.train <- dim(data) # training data dimensions
    dim.out <- if(type == "GMMN") {
                   dim[length(dim)] # dimension of the output layer of GMMNs
               } else {
                   dim[1] # for VAEs, the dimension of input and output layers are equal
               }
    if(dim.train[2] != dim.out)
        stop("The dimension of the training data does not match the dimension of the output layer of the GNN")
    switch(type, # model (and checks) to train
           "GMMN" = {
               GNN <- GMMN_model(dim, ...)
               prior <- matrix(rnorm(dim.train[1] * dim[1]), nrow = dim.train[1]) # N(0,1) prior (same dimension as input layer)
               GNN %>% fit(x = prior, y = data,
                           batch_size = batch.size, epochs = nepoch) # training
           },
           "VAE" = {
               GNN <- VAE_model(dim, ...)
               GNN$model %>% fit(x = data, y = data, # ... for how we defined the loss function
                                 batch_size = batch.size, epochs = nepoch)
           },
           stop("Wrong 'type'"))
    GNN
}

##' @title Training or Loading a Trained GMMN
##' @param dim see ?GMMN_model
##' @param data see ?train
##' @param batch.size see ?train
##' @param nepoch see ?train
##' @param file character string (with or without ending .rda) specifying the file
##'        to save the trained GMMN to
##' @param name name under which the trained GMMN is saved in 'file'
##' @param package package name from which to load the object or NULL (the default)
##'        in which case the current working directory is searched.
##' @param ... additional arguments passed to the underlying train()
##' @return trained or loaded GMMN
##' @author Marius Hofert
GMMN_train_once <- function(dim, data, batch.size, nepoch,
                            file, name = rm_ext(basename(file)),
                            package = NULL, ...)
{
    if(exists_rda(file, objnames = name, package = package)) { # check existence of 'name' in 'file' (in package 'package' or current working directory if package = NULL)
        unserialize_model(read_rda(name, file = file, package = package),
                          custom_objects = c(loss = loss)) # get and return
    } else { # does not exist
        GMMN <- train(dim, data = data, batch.size = batch.size, nepoch = nepoch,
                      type = "GMMN", ...) # train
        save_rda(serialize_model(GMMN), file = file, names = name) # save (by side-effect)
        GMMN
    }
}

##' @title Training or Loading a Trained VAE
##' @param dim see ?VAE_model
##' @param model if provided, the model to be filled with weights if .rda exists;
##'        otherwise such a model is generated by a call to VAE_model()
##' @param data see ?train
##' @param batch.size see ?train
##' @param nepoch see ?train
##' @param file character string (with or without ending .rda) specifying the file
##'        to save the trained VAE to
##' @param name name under which the trained VAE is saved in 'file'
##' @param ... additional arguments passed to the underlying VAE_model (if the object
##'        doesn't exist) or the underlying train() (if the object already exists)
##' @return trained or loaded VAE
##' @author Marius Hofert
VAE_train_once <- function(dim, model, data, batch.size, nepoch,
                           file, name = rm_ext(basename(file)), ...)
{
    if(exists_rda(file, objnames = name, package = NULL)) { # check existence of 'name' in 'file' in the current working directory
        VAE <- if(hasArg(model)) model else VAE_model(dim, ...)
        unserialize_weights(VAE$model, read_rda(name, file = file, package = package)) # get and return
    } else { # does not exist
        VAE <- train(dim, data = data, batch.size = batch.size, nepoch = nepoch,
                     type = "VAE", ...) # train
        save_rda(serialize_weights(VAE$model), file = file, names = name) # save (by side-effect)
        VAE
    }
}
